### ISSUE TITLE
Dashboards in different folders

### ISSUE THREAD

**Issue by mig4** [grafana/grizzly#149]
Hi, we're looking into using grizzly to generate dashboards for use with [Grafana Provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/), so I'm looking to setup a CI workflow that runs `grr export` to generate dashboard JSON files in specific folder(s) so that they're picked up when the next CI step builds a Helm chart with those JSON files in a `ConfigMap`.

Also, we currently use a folder structure for the dashboards (in source repo) that I'm trying to preserve in the Helm chart (due to some splitting we're doing in the chart itself).

Currently if I structure the dashboards like:

```
# dashboards/folder1/dash1.jsonnet
{
  grafanaDashboardFolder:: 'folder1'
  grafanaDashboards+:: {
    'dash1.json': ...
  }
}
```

```
# dashboards/dashboards.jsonnet
(import 'folder1/dash1.jsonnet')
```

and run `grr export dashboards/dashboards.jsonnet out-dir`, I get:

```
# out-dir/Dashboard/folder1.json
""
```

```
# out-dir/Dashboard/dash1.json
{
  "uid": "dash1",
  ...
}
```

Questions:

- Where is the `Dashboard/` folder coming from? Is there any way I can disable/remove it from the output?
- The `grafanaDashboardFolder` setting seems to cause a JSON with an empty string be generated in the output directory but doesn't affect the dashboard JSON or its location at all. Is this a bug? Or am I misunderstanding the purpose of the setting?
- Is there any way I can cause `dash1.json` to be output to `out-dir/folder1/dash1.json`?

**Comment by malcolmholmes** [comment]
Grizzly is predominantly directed at the Grafana API, as file based provisioning is "almost" deprecated. With the API plus Grizzly's enveloped resources, dashboards can now easily be aligned with folders. Please re-open if still an issue.

**Comment by edobry** [comment]
@malcolmholmes sorry for necroing, but could you please share more details about file-based provisioning being deprecated? I searched but couldn't find anything about this

**Comment by malcolmholmes** [comment]
I did say "almost" rather than actually. I'm sure it's still the case (although I don't know for sure - I no longer work at Grafana Labs).

What was clear to me was that the APIs were getting the effort, not file based. Installing Grafana in such a way that you have access to the file system is becoming increasingly less common, so investing in extending the file based provisioning makes less sense. I'm not expecting it to be removed any time soon, but at the same time, I'd be surprised if any new features (or resource types) were added.
