### ISSUE TITLE
Use grizzly with multiple file output jsonnet feature

### ISSUE THREAD

**Issue by NicoAdrian** [grafana/grizzly#166]
I have a jsonnet file and I'm able to generate multiple json file out of it by using the `-m` option. How can I combine this option with grizzly main file ? 
When trying to import my jsonnet file in the grafanaDashboards field, grizzly says that my dashboard has no UID set.

**Comment by malcolmholmes** [comment]
When using Jsonnet and Grizzly, you want to render a single Jsonnet tree, so `-m` doesn't make so much sense here.

The `no UID` issue is because your JSON for the dashboard isn't reporting a UID - without a UID in the dashboard, Grizzly won't know how to refer to it a second time once it is uploaded. Just add a `"uid"` element to the root of your dashboard JSON, sticking to alphanum and dashes (I think is the rule).
