### ISSUE TITLE
Add support of custom Jsonnet library paths

### ISSUE THREAD

**Issue by HabibMAALEM** [grafana/grizzly#24]
Configuration variable **JsonnetPath** is present in [pkg/grizzly/config.go](https://github.com/grafana/grizzly/blob/master/pkg/grizzly/config.go#L11) but not used. It is really desirable to have the possibility of defining a specific path for Jsonnet libraries.
```golang
// Config provides configuration to `grafana-dash`
type Config struct {
	GrafanaURL  string
	JsonnetPath string
}
```
Also it will be a plus to have the possibility of override the path with the environment variable **JSONNET_PATH**

**Comment by malcolmholmes** [comment]
I think this was added before Grizzly absorbed Tanka code that does this for us.

The code currently imports code within the `lib` directory and the `vendor` directory, following Tanka's lead.

What is your usecase where something different would be useful?

**Comment by HabibMAALEM** [comment]
What i want, is to make it flexible and load libraries from any path using `JSONNET_PATH` variable not only `vendor` or `lib`

**Comment by luizberti** [comment]
Has any progress been done on this?

The standard behavior of tools in the Jsonnet community is to honor `JSONNET_PATH`, or at least expose your own variable to set it (e.g. `KUBECFG_JPATH`). Dictating the structure of other people's repositories is not good citizenship.

My use case, for example, is that we keep all vendored code under `third_party` at the repository root, rather than having it scattered all over the repo. Grizzly not supporting this means I have to tack a symlink in there for it to work, which makes other tools behave in a wonky manner.

Not everyone uses tanka (in fact, the excessive prescriptive workflow it enforces is the reason we chose `kubecfg` instead), and most people would expect this to adopt standardized behaviour, rather than deviating.

**Comment by malcolmholmes** [comment]
@luizberti Firstly, please remember that Grizzly is still extremely young (if actually quite useful).

What I want to avoid is situations where execution on two different workstations gives different results, hence supporting environment variables doesn't really work for me.

In Tanka, we could have the `spec.json` file that contains configs specific to an environment. There's also a largely unused `tkrc.yaml` file at the project root (and a suggestion that we replace this with a `project.json` file). Any of these would seem reasonable places to put jpath configs, especially if used in conjunction with Tanka's [jpath](https://github.com/grafana/tanka/blob/master/pkg/jsonnet/jpath/jpath.go) code, aimed at making code work regardless of working directory.

Given Grizzly is so young, and inherits much of this from Tanka, I would suggest adding the feature to Tanka so that it can be imported back here.

**Comment by mavimo** [comment]
@malcolmholmes I see that grizzly is not using the same approach is now on tanka, I'm not sure the two project should have the same behaviours since they can be used from people that need to manage grafana dashboards without embracing tanka (and all the logics that are behind that).

Looking into grizzly code I also see that there is a config value that is not used, is that supposed to host the list of path to looking for jsonnet path discovery? If you agree with the approach I'll open a pull request to:

 - move default json path (`vendor`, `lib`, `,`) in the `Config` object
 - allow `grizzly.evalToString` to use config value for json path
 - allow grizzly command to accept a flag to specify a new json path so do not depends from the ENV variable

That's looks fine for you?

**Comment by malcolmholmes** [comment]
Yes, that seems fair. I much prefer a command line argument to an environment variable given it will have such a significant influence on program flow.

I have my own thoughts about where Grizzly should go, and I am seeing Jsonnet become just one mode of operation. As well as Jsonnet, I an see it being able to process a directory of static files. There's lots of fun we can have with a tool like that.

**Comment by mavimo** [comment]
@malcolmholmes I understand

I try to make a PoC of the `jpath` flag usage (I'm not really convinced of the current implementation), I'll try to re-work it in the next days, at the moment I'm testing the current implementation and seems to work fine...

**Comment by mavimo** [comment]
@HabibMAALEM @luizberti I made a PR with this feature, if you have time to test it and give me some feedback to understand if I'm missing something would be awesome! :)
