### ISSUE TITLE
[Bug]: Misleading/incorrect errors

### ISSUE THREAD

**Issue by howardjohn** [grafana/grizzly#449]
### Grizzly Version

v0.4.2

### Expected Behavior

Should be able to watch with spec-only OR have a valid error

### Actual Behavior

```
$ grr watch . main.libsonnet
Providers: Grafana - active, Mimir - inactive (mimir address is not set), Synthetic Monitoring - inactive (stack id is not set)
INFO[0000] Watching for changes
INFO[0001] Changes detected. Parsing
INFO[0001] Changes detected. Applying ./main.libsonnet
ERRO[0001] Error: parse error in './main.libsonnet': folder (-f) required with --onlyspec
$ grr watch --help
Providers: Grafana - active, Mimir - inactive (mimir address is not set), Synthetic Monitoring - inactive (stack id is not set)
2024/05/30 18:53:20 Usage:
  grr watch <dir-to-watch> <resource-path> [flags]

Flags:
  -h, --help               help for watch
  -J, --jpath strings      Specify an additional library search dir (right-most wins) (default [vendor,lib,.])
  -l, --log-level string   info, debug, warning, error (default "info")
  -o, --output string      Output format
  -t, --target strings     resources to target

```

`-f` and `--onlyspec` are not valid flags. Also, the `--onlyspec` is `--only-spec` on the commands it is on?

**Comment by malcolmholmes** [comment]
Thanks for pointing this out. The reason you are seeing this is because your jsonnet contains a dashboard, but you have not specified a folder for that dashboard. You can either do so using the `metadata/folder` attribute in the JSON envelope that wraps the dashboard JSON itself, or you can set a single folder for all dashboards with `-f`, if your dashboard is raw JSON (no envelope), in which case, you'll also need to set `--only-spec`. Immediate fix: use envelopes and specify the folder.

#450 should fix this for the future.

**Comment by howardjohn** [comment]
@malcolmholmes the issue here is many of the commands, even ones that say to use --only-spec, do not accept this flag. Like `watch`

**Comment by malcolmholmes** [comment]
@howardjohn #450 added these flags to `watch`, didn't it? Am I missing something?

**Comment by howardjohn** [comment]
Looks like it.
