### ISSUE TITLE
[Bug]: Watch command doesn't make use of resource path argument

### ISSUE THREAD

**Issue by vincent-ehl** [grafana/grizzly#456]
### Grizzly Version

v0.4.2

### Expected Behavior

Running the watch command, I expect the directory in <dir-to-watch> to be watched and on any change of a file in this directory, the <resource-path> file should be executed and applied.

I hope I didn't misunderstand the resource-path argument, but this is how I interpret https://grafana.github.io/grizzly/workflows/#grr-watch.

### Actual Behavior

Changing a file in the <dir-to-watch> directory causes this file to be executed and applied, instead of the file given in <resource-path>.

### Steps to Reproduce

1. Create a basic grr.jsonnet and my-lib.libsonnet file:

```jsonnet
// grr.jsonnet
local grr = import 'grizzly/grizzly.libsonnet';
local myLib = import './my-lib.libsonnet';

{
  folders: [],
  dashboards: [
    grr.dashboard.new('my-dashboard', myLib)
  ]
}
```

```jsonnet
// my-lib.libsonnet
local g = import 'github.com/grafana/grafonnet/gen/grafonnet-latest/main.libsonnet';

g.dashboard.new('My Dashboard')
+ g.dashboard.withUid('my-dashboard')
```

2. Run the watch command: `grr watch . grr.jsonnet`
3. Resave the my-lib.libsonnet file to trigger the watcher

The following output should be visible:
```
INFO[0002] Changes detected. Parsing                    
INFO[0002] Changes detected. Applying my-lib.libsonnet  
ERRO[0002] Error: parse error in 'my-lib.libsonnet': found invalid object (at .): errors parsing resource: kind missing, metadata missing, spec missing
```

**Comment by thampiotr** [comment]
I have the same issue, which appears to be a regression since the previous `2.x` version we have used. 

The `watch` command takes two positional arguments. The first one is the path to set up the watcher for and the second is the grizzly config file that should be reloaded when changes are detected by the watcher. 

What happens instead is that the path of the file that has been modified is attempted to be reloaded, instead of the path provided in the second positional argument (the grizzly config file). 

This can be reproduced with:

dash.libsonnet:
```
{
    folderName: "test",
}
```

grizzly.jsonnet:
```
local mixin = import "./dash.libsonnet";

{
  folder: {
    apiVersion: 'grizzly.grafana.com/v1alpha1',
    kind: 'DashboardFolder',
    metadata: {
      name: 'test-folder',
    },
    spec: {
      title: mixin.folderName,
    },
  },
}
```
Then run: ` GRAFANA_URL=http://localhost:3000 grr watch -l debug ./ ./grizzly.jsonnet`
and go to modify the `dash.libsonnet`. You will get the following:

```
➜  repro git:(main) ✗ GRAFANA_URL=http://localhost:3000 grr watch -l debug ./ ./grizzly.jsonnet
Providers: Grafana - active, Mimir - inactive (mimir address is not set), Synthetic Monitoring - inactive (stack id is not set)
INFO[0000] Watching for changes
INFO[0006] Changes detected. Parsing
INFO[0006] Changes detected. Applying dash.libsonnet
DEBU[0006] recursion ended on key "folderName" of type string which does not belong to a valid resource
ERRO[0006] Error: parse error in 'dash.libsonnet': found invalid object (at .): errors parsing resource: kind missing, metadata missing, spec missing

folderName: test
grafana:
    dashboards: {}
    datasources: {}
    folders: null
prometheus: []
syntheticMonitoringChecks: {}
```

This is identical error to what you get if you run `GRAFANA_URL=http://localhost:3000 grr apply -l debug ./dash.libsonnet`, so that's why I believe that the wrong path is being provided to apply to the remote.

**Comment by maxlapshin** [comment]
I'm sorry, but it is still actual in 0.6.0

```
$ grr --version
2024/11/30 12:41:07 grr version 0.6.0
```

```
$ grr serve -w grafana/provisioning/dashboards/*.json
Listening on http://localhost:8080/
INFO [watcher] Watching for changes               
ERROR [watcher] Error: parse error in 'grafana/provisioning/dashboards/teledis-monitoring.json': found invalid object (at .): errors parsing resource: kind missing, metadata missing, spec missing

description: TV hub monitoring
graphTooltip: 1
refresh: 10s
schemaVersion: 39
tags:
    - tr101290
time:
    from: now-6h
    to: now
timezone: utc
title: My Dashboard
uid: teledis2 
```

**Comment by malcolmholmes** [comment]
@maxlapshin that isn't necessarily a bug. It suggests that your data (in `teledis-monitoring.json`) isn't in a format that Grizzly can understand.

It should either be a raw dashboard, or be in the "kubernetes style" layout. What is the content of that file? I notice you refer to a json file then present a snippet of YAML?

The above snippet wouldn't be considered a valid dashboard, because Grizzly identifies a dashboard as a JSON/YAML with these keys: `panels`, `title` and `schemaVersion`. Yours only has one of these three.

**Comment by maxlapshin** [comment]
Great! Thanks for your comment.  I was trying to make a minimal dashboard via grafonnet and while making it minimal, I could lose panels.

Will repeat it with adding these three minimal keys.
